version: "3"

services:
  go:
    build: .
    container_name: go
    volumes:
      - /home/ubuntu/kakeibo_docker/go/go/main:/go/src/main
    networks:
      - reactapp
    tty: true
    stdin_open: true
    command: sh -c "cd /go/src/main && go run main.go"
  react-db:
    build: ../db
    container_name: react-db
    volumes:
      - reactdb:/var/lib/mysql
    networks:
      - reactapp
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: shopping
  react:
    build: ../react
    container_name: react
    volumes:
      - /home/ubuntu/kakeibo_docker/react/:/usr/src/app
    command: sh -c "cd EC2container && npm start"
    tty: true
    stdin_open: true
    networks:
      - reactapp
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - /home/ubuntu/kakeibo_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reactapp
networks:
  reactapp:
    external: true
volumes:
  reactdb:
